from dataclasses import dataclass
from typing import Optional, Literal, Dict

from Knowledge.Schema.Artifacts.datasources import (
    DataSource,
    sec_edgar_api_source,
)


AssetKind = Literal["remote_api", "local_folder", "local_file", "vector_index"]


@dataclass
class DataAsset:
    """Declarative description of a data asset used in the workflow."""
    key: str
    kind: AssetKind
    description: str

    # For local folders / files
    path: Optional[str] = None

    # For vector indices / RAG collections
    collection: Optional[str] = None

    # Upstream source metadata (who owns this data)
    source: Optional[DataSource] = None


class DataRegistry:
    """Central registry for all data assets in the 10-K workflow."""

    def __init__(self) -> None:
        self._assets: Dict[str, DataAsset] = {}

        # ── Remote APIs ───────────────────────────────────────────────
        self._register(
            DataAsset(
                key="sec_edgar_filings",
                kind="remote_api",
                description="SEC EDGAR submissions + 10-K document API",
                source=sec_edgar_api_source(
                    notes="Used by IdentifyStage and FetchStage."
                ),
            )
        )

       

        # ── Local folders ────────────────────────────────────────────
        self._register(
            DataAsset(
                key="reports_folder",
                kind="local_folder",
                description="Folder where 10-K SummaryReports are written.",
                path="Data/Outputs/reports",
            )
        )

        # ── Vector indices / RAG collections ─────────────────────────
        self._register(
            DataAsset(
                key="pinecone_10k_chunks",
                kind="vector_index",
                description="Pinecone index for 10-K chunks (risk factors, 7A, 8, etc.).",
                collection="knowledgepinecone",
                source=sec_edgar_api_source(
                    notes="Chunks are derived from SEC 10-K text."
                ),
            )
        )

        self._register(
            DataAsset(
                key="pinecone_10k_summaries",
                kind="vector_index",
                description="Pinecone index entries for final 10-K summary vectors.",
                collection="knowledgepinecone",  # same collection, different content_type
                source=sec_edgar_api_source(
                    notes="Summary vectors generated by SummarizerAgent and run_from_sec."
                ),
            )
        )

    # ────────────────────────────────────────────────────────────────
    # Helpers
    # ────────────────────────────────────────────────────────────────

    def _register(self, asset: DataAsset) -> None:
        if asset.key in self._assets:
            raise ValueError(f"Data asset with key '{asset.key}' already registered")
        self._assets[asset.key] = asset

    def get(self, key: str) -> DataAsset:
        if key not in self._assets:
            raise KeyError(f"Unknown data asset key: {key}")
        return self._assets[key]

    def all(self) -> Dict[str, DataAsset]:
        return dict(self._assets)


# Single global registry instance you can import anywhere
data_registry = DataRegistry()
